language: minimal

services:
  - docker

env:
  - NIM_VERSION=1.4.2
  - NIM_VERSION=1.2.6
  - NIM_VERSION=1.0.6

install:
  - docker-compose build --build-arg NIM_VERSION=$NIM_VERSION

script:
  - docker-compose run --rm nimble test
