version: '3'
services:
  postgres:
    image: postgres:11
    environment:
    - POSTGRES_PASSWORD=postgres
  nimble:
    build: utils
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    entrypoint: nimble
    working_dir: /usr/src/app
