version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  tests:
    build: .
    image: lowdb
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: nimble test

  book:
    build: .
    image: lowdb
    volumes:
      - .:/usr/src/app
    command: nimble nimidocs