name: tests.yml - Running tests

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - devel
      - master

jobs:
  Tests:
    runs-on: postgres
    strategy:
      matrix:
        nim-version: ['1.0.6', '1.2.6', '1.4.2', 'stable', 'devel']
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble install -Y
      - run: nimble tests -Y