name: tests.yml - Running tests

on:
  push:
    branches:
      - devel
      - master
      - CI-passing
  pull_request:
    branches:
      - devel
      - master

jobs:
  Tests:
    timeout-minutes: 30

    runs-on: ubuntu-latest
    container: ubuntu:latest

    strategy:
      matrix:
        nim-version: ['1.0.6', 'stable']
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Nim ${{ matrix.nim }}

    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble install -Y
      - run: nimble test -Y
